FROM python:3.5

ENV POSTS_GIT_REPO "https://github.com/jradd/blogposts"
ENV POSTS_GIT_REPO_SECRET "4a23b1b45cdaef7ddb68828627c743574684deba"

RUN mkdir www && cd $_ && \
	git clone https://github.com/jradd/blog && \
	cd blog && \
	pip install -r Requirements.in && \
	cd app && \
	git clone $POSTS_GIT_REPO

WORKDIR /www/blog/app

EXPOSE 5000

CMD ["python3", "app.py"]

